// ─── QUOTE DATABASE: 200+ quotes across 4 languages ──────────────────────────

export const QUOTES = {
  english: [
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "Motivation" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", category: "Wisdom" },
    { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle", category: "Courage" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "Dreams" },
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", category: "Persistence" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "Motivation" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", category: "Wisdom" },
    { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs", category: "Life" },
    { text: "The mind is everything. What you think you become.", author: "Buddha", category: "Wisdom" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein", category: "Success" },
    { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison", category: "Persistence" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "Courage" },
    { text: "Life is what happens when you're busy making other plans.", author: "John Lennon", category: "Life" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "Life" },
    { text: "Get busy living or get busy dying.", author: "Stephen King", category: "Life" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "Courage" },
    { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", category: "Motivation" },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", category: "Dreams" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", category: "Wisdom" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair", category: "Courage" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James", category: "Motivation" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "Wisdom" },
    { text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama", category: "Life" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra", category: "Success" },
    { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington", category: "Wisdom" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis", category: "Persistence" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson", category: "Persistence" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Motivation" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela", category: "Courage" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "Dreams" },
    { text: "What we achieve inwardly will change outer reality.", author: "Plutarch", category: "Wisdom" },
    { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", category: "Persistence" },
    { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", category: "Life" },
    { text: "In three words I can sum up everything I learned about life: it goes on.", author: "Robert Frost", category: "Life" },
    { text: "If you look at what you have in life, you'll always have more.", author: "Oprah Winfrey", category: "Wisdom" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "Motivation" },
    { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", category: "Success" },
    { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson", category: "Success" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson", category: "Life" },
    { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau", category: "Dreams" },
    { text: "When one door of happiness closes, another opens.", author: "Helen Keller", category: "Life" },
    { text: "The best way to predict the future is to create it.", author: "Peter Drucker", category: "Dreams" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", category: "Wisdom" },
    { text: "We become what we think about most of the time.", author: "Earl Nightingale", category: "Wisdom" },
    { text: "Nothing is impossible, the word itself says 'I'm possible'!", author: "Audrey Hepburn", category: "Motivation" },
    { text: "Don't count the days, make the days count.", author: "Muhammad Ali", category: "Life" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan", category: "Dreams" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "Persistence" },
    { text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh", category: "Courage" },
    { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", category: "Motivation" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", category: "Courage" },
    { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", category: "Wisdom" },
    { text: "The most wasted of all days is one without laughter.", author: "E.E. Cummings", category: "Life" },
  ],
  hindi: [
    { text: "जो बीत गई सो बात गई, जीवन में एक सितारा था, माना वह बेहद प्यारा था, वह डूब गया तो डूब गया, अम्बर के आनन को देखो, कितने इसके तारे टूटे, कितने इसके प्यारे छूटे, पर बोलो टूटे तारों पर, कब अम्बर शोक मनाता है।", author: "हरिवंश राय बच्चन", category: "कविता" },
    { text: "लहरों से डरकर नौका पार नहीं होती, कोशिश करने वालों की कभी हार नहीं होती।", author: "हरिवंश राय बच्चन", category: "कविता" },
    { text: "मुट्ठी में है तकदीर हमारी, हम स्वयं बनाएं या बिगाड़ें।", author: "सुभद्रा कुमारी चौहान", category: "प्रेरणा" },
    { text: "खुद को कमज़ोर समझना सबसे बड़ा पाप है।", author: "स्वामी विवेकानंद", category: "प्रेरणा" },
    { text: "उठो, जागो और तब तक मत रुको जब तक लक्ष्य की प्राप्ति न हो जाए।", author: "स्वामी विवेकानंद", category: "प्रेरणा" },
    { text: "बुरा जो देखन मैं चला, बुरा न मिलिया कोय, जो दिल खोजा आपना, मुझसे बुरा न कोय।", author: "कबीर दास", category: "दोहा" },
    { text: "पोथी पढ़ि पढ़ि जग मुआ, पंडित भया न कोय, ढाई आखर प्रेम का, पढ़े सो पंडित होय।", author: "कबीर दास", category: "दोहा" },
    { text: "चलती चक्की देख के, दिया कबीरा रोये, दो पाटन के बीच में, साबुत बचा न कोये।", author: "कबीर दास", category: "दोहा" },
    { text: "साईं इतना दीजिए, जा में कुटुम समाय, मैं भी भूखा न रहूँ, साधु ना भूखा जाय।", author: "कबीर दास", category: "दोहा" },
    { text: "धीरे-धीरे रे मना, धीरे सब कुछ होय, माली सींचे सौ घड़ा, ऋतु आए फल होय।", author: "कबीर दास", category: "दोहा" },
    { text: "दुख में सुमिरन सब करे, सुख में करे न कोय, जो सुख में सुमिरन करे, तो दुख काहे को होय।", author: "कबीर दास", category: "दोहा" },
    { text: "रहिमन धागा प्रेम का, मत तोरो चटकाय, टूटे से फिर ना जुड़े, जुड़े गाँठ पड़ जाय।", author: "रहीम दास", category: "दोहा" },
    { text: "जो रहीम उत्तम प्रकृति, का करि सकत कुसंग, चन्दन विष व्यापत नहीं, लिपटे रहत भुजंग।", author: "रहीम दास", category: "दोहा" },
    { text: "जहाँ चाह वहाँ राह।", author: "लोकोक्ति", category: "मुहावरा" },
    { text: "अकेला चना भाड़ नहीं फोड़ सकता — लेकिन शुरुआत तो एक से ही होती है।", author: "लोकोक्ति", category: "मुहावरा" },
    { text: "नाच न जाने आँगन टेढ़ा — बहाने बनाना बंद करो, शुरू करो।", author: "लोकोक्ति", category: "मुहावरा" },
    { text: "बंदर क्या जाने अदरक का स्वाद — सही लोगों तक अपनी बात पहुँचाओ।", author: "लोकोक्ति", category: "मुहावरा" },
    { text: "जो तोको काँटा बुवे, ताहि बोई तू फूल, तुझे फूल को फूल है, वाको है तिरशूल।", author: "कबीर दास", category: "दोहा" },
    { text: "सपनों को इतना बड़ा बनाओ कि हकीकत भी शर्मा जाए।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "कर्म करो, फल की चिंता मत करो — यही जीवन का सबसे बड़ा मंत्र है।", author: "गीता सार", category: "प्रेरणा" },
    { text: "गिरते हैं शहसवार ही मैदान-ए-जंग में, वो तिफ़्ल क्या गिरेंगे जो घुटनों के बल चलें।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "मन के हारे हार है, मन के जीते जीत।", author: "लोकोक्ति", category: "मुहावरा" },
    { text: "होनहार बिरवान के होत चीकने पात — प्रतिभा बचपन से दिखती है।", author: "लोकोक्ति", category: "मुहावरा" },
    { text: "करत-करत अभ्यास के, जड़मति होत सुजान, रसरी आवत जात ते, सिल पर परत निसान।", author: "वृंद", category: "दोहा" },
    { text: "ठोकर लगती है तो चोट लगती है, चोट लगती है तो सीख मिलती है, सीख मिलती है तो इंसान बनता है।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "हार कर बैठ जाना आसान है, जीतने के लिए लड़ना पड़ता है।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "जिंदगी में कभी किसी को कम मत समझो, हर खाली बर्तन में आवाज़ ज़्यादा होती है।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "बिना संघर्ष के कोई भी महान नहीं बन सकता।", author: "स्वामी विवेकानंद", category: "प्रेरणा" },
    { text: "अगर ज़िन्दगी में कुछ पाना है तो अपने तरीके बदलो, इरादे नहीं।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "विश्वास वह पक्षी है जो प्रभात के पूर्व अँधेरे में ही प्रकाश अनुभव करता है।", author: "रवींद्रनाथ टैगोर", category: "कविता" },
    { text: "जो बदल सके खुद को वही बदल सकता है दुनिया को।", author: "महात्मा गांधी", category: "प्रेरणा" },
    { text: "अब तक क्या किया, जीवन क्या जिया, ज़्यादा लिया और दिया बहुत कम।", author: "अटल बिहारी वाजपेयी", category: "कविता" },
    { text: "कल करे सो आज कर, आज करे सो अब, पल में परलय होएगी, बहुरि करेगा कब।", author: "कबीर दास", category: "दोहा" },
    { text: "तुलसी साथी विपत्ति के, विद्या विनय विवेक, साहस सुकृति सुसत्यव्रत, राम भरोसे एक।", author: "तुलसीदास", category: "दोहा" },
    { text: "सबसे बड़ी सज़ा यह है कि आप अपनी ज़िंदगी ख़ुद न जी सकें।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "मंज़िल उन्हीं को मिलती है जिनके सपनों में जान होती है, पंखों से कुछ नहीं होता हौसलों से उड़ान होती है।", author: "अज्ञात", category: "कविता" },
    { text: "चिड़िया चोंच भर पानी पीती है, फिर आसमान की ओर देखती है — शुक्रगुज़ार होना सीखो।", author: "लोकोक्ति", category: "मुहावरा" },
    { text: "बड़ा सोचो, बड़ा करो — छोटी सोच से बड़ा कभी कुछ नहीं बनता।", author: "धीरूभाई अंबानी", category: "प्रेरणा" },
    { text: "दीवार पर चींटी चढ़ती है, गिरती है, फिर चढ़ती है — यही जीवन है।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "आँखों में जो सपने हैं, उनमें जान डालो, रास्ते खुद बन जाएंगे।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "कोशिश करने वालों की कभी हार नहीं होती, लहरों से डर कर नौका पार नहीं होती।", author: "सोहन लाल द्विवेदी", category: "कविता" },
    { text: "जो व्यक्ति अपने क्रोध को वश में कर लेता है, वही सबसे बड़ा योद्धा है।", author: "चाणक्य", category: "प्रेरणा" },
    { text: "असफलता एक चुनौती है, स्वीकार करो, क्या कमी रह गई, देखो और सुधार करो।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "सफलता वहीं मिलती है जहाँ हमारी तैयारी और अवसर मिलते हैं।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "बुराई को देखना और सुनना ही बुराई की शुरुआत है।", author: "महात्मा गांधी", category: "प्रेरणा" },
    { text: "दो पल की ज़िन्दगी में, हज़ारों ख़्वाब सजा लो, जो पूरे हो जाएं उनसे अच्छा क्या।", author: "अज्ञात", category: "कविता" },
    { text: "जिसने धूप में चलना सीख लिया, उसे छाँव की ज़रूरत नहीं होती।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "एक दीया जो अपने धुएँ से नहीं डरता, वो हज़ारों को रोशनी देता है।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "ज़िन्दगी की किताब के पन्ने खुद लिखने पड़ते हैं, नसीब के भरोसे बैठने वाले अक्सर खाली रह जाते हैं।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "वक्त बदलता है, हालात बदलते हैं, मेहनत करने वालों की किस्मत बदलती है।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "निराशा एक अभिशाप है और आशा जीवन का आधार।", author: "प्रेमचंद", category: "प्रेरणा" },
  ],
  sanskrit: [
    { text: "कर्मण्येवाधिकारस्ते मा फलेषु कदाचन। मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥", author: "भगवद्गीता 2.47", translation: "तुम्हारा अधिकार केवल कर्म करने में है, फल में कभी नहीं। कर्म के फल का कारण मत बनो और कर्म न करने में भी तुम्हारी आसक्ति न हो।", category: "कर्म" },
    { text: "योगः कर्मसु कौशलम्।", author: "भगवद्गीता 2.50", translation: "कर्म में कुशलता ही योग है।", category: "कर्म" },
    { text: "उद्धरेदात्मनात्मानं नात्मानमवसादयेत्। आत्मैव ह्यात्मनो बन्धुरात्मैव रिपुरात्मनः॥", author: "भगवद्गीता 6.5", translation: "अपने आप को स्वयं ऊपर उठाओ, अपने आप को गिराओ नहीं। आत्मा ही अपना मित्र है और आत्मा ही अपना शत्रु है।", category: "आत्मज्ञान" },
    { text: "विद्या ददाति विनयम्, विनयाद्याति पात्रताम्। पात्रत्वाद्धनमाप्नोति, धनाद्धर्मं ततः सुखम्॥", author: "हितोपदेश", translation: "विद्या विनय देती है, विनय से पात्रता आती है, पात्रता से धन मिलता है, धन से धर्म और धर्म से सुख मिलता है।", category: "विद्या" },
    { text: "सत्यमेव जयते नानृतम्।", author: "मुण्डक उपनिषद्", translation: "सत्य की ही विजय होती है, असत्य की नहीं।", category: "सत्य" },
    { text: "अहिंसा परमो धर्मः।", author: "महाभारत", translation: "अहिंसा सबसे बड़ा धर्म है।", category: "धर्म" },
    { text: "सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः। सर्वे भद्राणि पश्यन्तु मा कश्चिद्दुःखभाग्भवेत्॥", author: "उपनिषद्", translation: "सभी सुखी हों, सभी निरोग हों, सभी का कल्याण हो, कोई भी दुखी न हो।", category: "कल्याण" },
    { text: "वसुधैव कुटुम्बकम्।", author: "मह उपनिषद्", translation: "सारा संसार एक परिवार है।", category: "कल्याण" },
    { text: "अयं निजः परो वेति गणना लघुचेतसाम्। उदारचरितानां तु वसुधैव कुटुम्बकम्॥", author: "हितोपदेश", translation: "यह अपना है, यह पराया है — ऐसा संकीर्ण लोग सोचते हैं। उदार हृदय वालों के लिए तो सारा संसार ही परिवार है।", category: "कल्याण" },
    { text: "न हि ज्ञानेन सदृशं पवित्रमिह विद्यते।", author: "भगवद्गीता 4.38", translation: "इस संसार में ज्ञान के समान पवित्र करने वाला कुछ भी नहीं है।", category: "विद्या" },
    { text: "श्रद्धावान् लभते ज्ञानम्।", author: "भगवद्गीता 4.39", translation: "श्रद्धा रखने वाला ज्ञान प्राप्त करता है।", category: "विद्या" },
    { text: "दूरेण ह्यवरं कर्म बुद्धियोगाद्धनञ्जय। बुद्धौ शरणमन्विच्छ कृपणाः फलहेतवः॥", author: "भगवद्गीता 2.49", translation: "बुद्धियोग से सकाम कर्म अत्यन्त निम्न है। बुद्धि की शरण लो — फल के लिए कर्म करने वाले कृपण हैं।", category: "कर्म" },
    { text: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत। अभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम्॥", author: "भगवद्गीता 4.7", translation: "जब-जब धर्म की हानि और अधर्म का उत्थान होता है, तब-तब मैं स्वयं को प्रकट करता हूँ।", category: "धर्म" },
    { text: "मनः प्रशमनोपायो योग इत्यभिधीयते।", author: "योग वशिष्ठ", translation: "मन को शांत करने का उपाय ही योग कहलाता है।", category: "योग" },
    { text: "असतो मा सद्गमय। तमसो मा ज्योतिर्गमय। मृत्योर्मा अमृतं गमय॥", author: "बृहदारण्यक उपनिषद्", translation: "असत्य से सत्य की ओर ले चलो। अंधकार से प्रकाश की ओर ले चलो। मृत्यु से अमरता की ओर ले चलो।", category: "सत्य" },
    { text: "ॐ सह नाववतु। सह नौ भुनक्तु। सह वीर्यं करवावहै।", author: "कठ उपनिषद्", translation: "हम दोनों की साथ रक्षा हो। हम दोनों साथ भोजन करें। हम दोनों साथ पुरुषार्थ करें।", category: "कल्याण" },
    { text: "विनाशकाले विपरीतबुद्धिः।", author: "हितोपदेश", translation: "विनाश काल आने पर बुद्धि उल्टी हो जाती है।", category: "विद्या" },
    { text: "सुखस्य मूलं धर्मः। धर्मस्य मूलं अर्थः। अर्थस्य मूलं राज्यम्।", author: "चाणक्य — अर्थशास्त्र", translation: "सुख का मूल धर्म है। धर्म का मूल अर्थ है। अर्थ का मूल राज्य है।", category: "धर्म" },
    { text: "प्रयत्नाद्यतमानस्तु योगी संशुद्धकिल्बिषः। अनेकजन्मसंसिद्धस्ततो याति परां गतिम्॥", author: "भगवद्गीता 6.45", translation: "प्रयत्नपूर्वक अभ्यास करने वाला योगी, पापों से शुद्ध होकर, अनेक जन्मों की सिद्धि से परम गति को प्राप्त होता है।", category: "योग" },
    { text: "नास्ति विद्यासमं चक्षुः नास्ति सत्यसमं तपः।", author: "महाभारत", translation: "विद्या के समान कोई नेत्र नहीं और सत्य के समान कोई तप नहीं।", category: "विद्या" },
    { text: "परोपकाराय फलन्ति वृक्षाः, परोपकाराय वहन्ति नद्यः। परोपकाराय दुहन्ति गावः, परोपकारार्थमिदं शरीरम्॥", author: "सुभाषित", translation: "वृक्ष दूसरों के लिए फलते हैं, नदियाँ दूसरों के लिए बहती हैं, गाएँ दूसरों के लिए दूध देती हैं — यह शरीर भी परोपकार के लिए है।", category: "कल्याण" },
    { text: "क्षणशः कणशश्चैव विद्यामर्थं च साधयेत्।", author: "हितोपदेश", translation: "एक-एक क्षण और एक-एक कण से विद्या और धन को साधना चाहिए।", category: "विद्या" },
    { text: "अलसस्य कुतो विद्या, अविद्यस्य कुतो धनम्। अधनस्य कुतो मित्रम्, अमित्रस्य कुतः सुखम्॥", author: "चाणक्य नीति", translation: "आलसी को विद्या कहाँ, अनपढ़ को धन कहाँ, निर्धन को मित्र कहाँ, और मित्रहीन को सुख कहाँ।", category: "विद्या" },
    { text: "ज्ञानं भारः क्रियां बिना।", author: "सुभाषित", translation: "बिना कर्म के ज्ञान बोझ है।", category: "कर्म" },
    { text: "शरीरमाद्यं खलु धर्मसाधनम्।", author: "कुमारसम्भवम्", translation: "शरीर ही धर्म का पहला साधन है।", category: "योग" },
    { text: "मनसा चिन्तितं कार्यं वाचा नैव प्रकाशयेत्।", author: "चाणक्य नीति", translation: "मन में सोचे हुए कार्य को वाणी से प्रकट नहीं करना चाहिए।", category: "आत्मज्ञान" },
    { text: "काकचेष्टा बकध्यानं श्वाननिद्रा तथैव च। अल्पाहारी गृहत्यागी विद्यार्थी पञ्चलक्षणम्॥", author: "चाणक्य नीति", translation: "कौए जैसी चेष्टा, बगुले जैसा ध्यान, कुत्ते जैसी नींद, अल्प आहार और गृह त्याग — ये विद्यार्थी के पाँच लक्षण हैं।", category: "विद्या" },
    { text: "धर्मो रक्षति रक्षितः।", author: "मनुस्मृति", translation: "धर्म की रक्षा करने वाले की धर्म रक्षा करता है।", category: "धर्म" },
    { text: "संघे शक्तिः कलौ युगे।", author: "वेद", translation: "कलियुग में एकता में ही शक्ति है।", category: "कल्याण" },
    { text: "आत्मनं रथिनं विद्धि शरीरं रथमेव तु। बुद्धिं तु सारथिं विद्धि मनः प्रग्रहमेव च॥", author: "कठ उपनिषद्", translation: "आत्मा को रथी जानो, शरीर को रथ, बुद्धि को सारथी और मन को लगाम।", category: "आत्मज्ञान" },
    { text: "यत्र नार्यस्तु पूज्यन्ते रमन्ते तत्र देवताः।", author: "मनुस्मृति", translation: "जहाँ नारियों का सम्मान होता है, वहाँ देवता निवास करते हैं।", category: "धर्म" },
    { text: "सत्यं ब्रूयात् प्रियं ब्रूयात् न ब्रूयात् सत्यमप्रियम्।", author: "मनुस्मृति", translation: "सत्य बोलो, प्रिय बोलो, अप्रिय सत्य मत बोलो।", category: "सत्य" },
    { text: "मातृदेवो भव। पितृदेवो भव। आचार्यदेवो भव।", author: "तैत्तिरीय उपनिषद्", translation: "माता देवता समान है। पिता देवता समान है। आचार्य देवता समान है।", category: "धर्म" },
    { text: "ईश्वरः सर्वभूतानां हृद्देशेऽर्जुन तिष्ठति।", author: "भगवद्गीता 18.61", translation: "हे अर्जुन, ईश्वर सभी प्राणियों के हृदय में निवास करता है।", category: "आत्मज्ञान" },
    { text: "नायमात्मा बलहीनेन लभ्यः।", author: "मुण्डक उपनिषद्", translation: "बलहीन व्यक्ति आत्मा को प्राप्त नहीं कर सकता।", category: "आत्मज्ञान" },
    { text: "तमसो मा ज्योतिर्गमय।", author: "बृहदारण्यक उपनिषद्", translation: "अंधकार से प्रकाश की ओर मुझे ले चलो।", category: "सत्य" },
    { text: "योगश्चित्तवृत्तिनिरोधः।", author: "पतञ्जलि योगसूत्र", translation: "चित्त की वृत्तियों का निरोध ही योग है।", category: "योग" },
    { text: "सर्वं परवशं दुःखं सर्वमात्मवशं सुखम्।", author: "मनुस्मृति", translation: "दूसरों पर निर्भरता दुख है और आत्मनिर्भरता सुख है।", category: "आत्मज्ञान" },
    { text: "विद्या विवादाय धनं मदाय शक्तिः परेषां परिपीडनाय। खलस्य साधोर्विपरीतमेतद् ज्ञानाय दानाय च रक्षणाय॥", author: "सुभाषित", translation: "दुष्ट की विद्या विवाद के लिए, धन घमंड के लिए, शक्ति पीड़ा के लिए — सज्जन इसका विपरीत करते हैं: ज्ञान, दान और रक्षा के लिए।", category: "विद्या" },
    { text: "गुरुर्ब्रह्मा गुरुर्विष्णुः गुरुर्देवो महेश्वरः। गुरुः साक्षात् परं ब्रह्म तस्मै श्री गुरवे नमः॥", author: "गुरु स्तोत्र", translation: "गुरु ब्रह्मा हैं, गुरु विष्णु हैं, गुरु शिव हैं। गुरु साक्षात् परब्रह्म हैं — उन गुरु को नमस्कार।", category: "धर्म" },
    { text: "स्वभावो दुरतिक्रमः।", author: "भगवद्गीता", translation: "स्वभाव को बदलना अत्यंत कठिन है।", category: "आत्मज्ञान" },
    { text: "सत्येन धार्यते पृथ्वी।", author: "सुभाषित", translation: "सत्य से पृथ्वी टिकी हुई है।", category: "सत्य" },
    { text: "उत्तिष्ठत जाग्रत प्राप्य वरान्निबोधत।", author: "कठ उपनिषद्", translation: "उठो, जागो और श्रेष्ठ गुरुओं से ज्ञान प्राप्त करो।", category: "विद्या" },
    { text: "न चोरहार्यं न च राजहार्यं न भ्रातृभाज्यं न च भारकारी। व्यये कृते वर्धत एव नित्यं विद्याधनं सर्वधनप्रधानम्॥", author: "सुभाषित", translation: "विद्या रूपी धन को न चोर चुरा सकता है, न राजा छीन सकता है, न भाइयों में बँटता है, न बोझ लगता है। खर्च करने से बढ़ता है — विद्या सबसे श्रेष्ठ धन है।", category: "विद्या" },
    { text: "दैवी ह्येषा गुणमयी मम माया दुरत्यया। मामेव ये प्रपद्यन्ते मायामेतां तरन्ति ते॥", author: "भगवद्गीता 7.14", translation: "मेरी यह दैवी माया गुणमयी और दुर्लंघ्य है। जो मेरी शरण में आते हैं, वे इस माया को पार कर जाते हैं।", category: "आत्मज्ञान" },
    { text: "चित्ते प्रसन्ने भुवनं प्रसन्नम्।", author: "सुभाषित", translation: "जब मन प्रसन्न होता है तो सारा संसार प्रसन्न लगता है।", category: "योग" },
    { text: "अभ्यासेन तु कौन्तेय वैराग्येण च गृह्यते।", author: "भगवद्गीता 6.35", translation: "हे कुन्तीपुत्र, अभ्यास और वैराग्य से मन को वश में किया जा सकता है।", category: "योग" },
    { text: "सुखार्थिनः कुतो विद्या नास्ति विद्यार्थिनः सुखम्। सुखार्थी वा त्यजेद्विद्यां विद्यार्थी वा त्यजेत्सुखम्॥", author: "चाणक्य नीति", translation: "सुख चाहने वाले को विद्या कहाँ और विद्या चाहने वाले को सुख कहाँ। सुख चाहो तो विद्या छोड़ो, विद्या चाहो तो सुख छोड़ो।", category: "विद्या" },
    { text: "शनैः शनैरुपरमेद्बुद्ध्या धृतिगृहीतया।", author: "भगवद्गीता 6.25", translation: "धीरे-धीरे, धैर्य से पकड़ी हुई बुद्धि से मन को शांत करो।", category: "योग" },
  ],
  urdu: [
    { text: "हज़ारों ख़्वाहिशें ऐसी कि हर ख़्वाहिश पे दम निकले, बहुत निकले मेरे अरमान लेकिन फिर भी कम निकले।", author: "मिर्ज़ा ग़ालिब", category: "ग़ज़ल" },
    { text: "ज़िन्दगी तेरे ग़म ने हमें रिश्ता सिखाया, हँसना आता नहीं था तो रोना सिखाया।", author: "अहमद फ़राज़", category: "ग़ज़ल" },
    { text: "ख़ुदी को कर बुलंद इतना कि हर तक़दीर से पहले, ख़ुदा बन्दे से ख़ुद पूछे बता तेरी रज़ा क्या है।", author: "अल्लामा इक़बाल", category: "प्रेरणा" },
    { text: "सितारों से आगे जहाँ और भी हैं, अभी इश्क़ के इम्तिहाँ और भी हैं।", author: "अल्लामा इक़बाल", category: "प्रेरणा" },
    { text: "मोहब्बत में नहीं है फ़र्क़ जीने और मरने का, उसी को देख कर जीते हैं जिस काफ़िर पे दम निकले।", author: "मिर्ज़ा ग़ालिब", category: "इश्क़" },
    { text: "दिल-ए-नादाँ तुझे हुआ क्या है, आख़िर इस दर्द की दवा क्या है।", author: "मिर्ज़ा ग़ालिब", category: "ग़ज़ल" },
    { text: "गिरते हैं शहसवार ही मैदान-ए-जंग में, वो तिफ़्ल क्या गिरेंगे जो घुटनों के बल चलें।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "ज़माने के दस्तूर पे मत रो, अपनी तक़दीर बदलने की कोशिश करो।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "मुश्किलें मुझ पर पड़ीं इतनी कि आसाँ हो गईं।", author: "मिर्ज़ा ग़ालिब", category: "ज़िन्दगी" },
    { text: "ये इश्क़ नहीं आसाँ बस इतना समझ लीजे, एक आग का दरिया है और डूब के जाना है।", author: "जिगर मोरादाबादी", category: "इश्क़" },
    { text: "उम्र भर ग़ालिब यही भूल करता रहा, धूल चेहरे पर थी आईना साफ़ करता रहा।", author: "मिर्ज़ा ग़ालिब", category: "ज़िन्दगी" },
    { text: "इक ख़्वाब का मज़ा कुछ इस तरह ले रहा हूँ, सोता नहीं हूँ लेकिन ज़िन्दगी जी रहा हूँ।", author: "अज्ञात", category: "ज़िन्दगी" },
    { text: "वो हमसे भी ग़मगीन हैं जिन्हें दुनिया ख़ुश समझती है।", author: "अज्ञात", category: "ज़िन्दगी" },
    { text: "रंज़ से ख़ूगर हुआ इंसाँ तो मिट जाता है रंज़, मुश्किलें मुझ पर पड़ीं इतनी कि आसाँ हो गईं।", author: "मिर्ज़ा ग़ालिब", category: "ग़ज़ल" },
    { text: "लब पे आती है दुआ बन के तमन्ना मेरी, ज़िन्दगी शम्अ की सूरत हो ख़ुदाया मेरी।", author: "अल्लामा इक़बाल", category: "प्रेरणा" },
    { text: "न तू ज़मीन के लिए है न आसमान के लिए, ये दोनों जहाँ तेरे लिए हैं तू किसी और के लिए।", author: "अल्लामा इक़बाल", category: "प्रेरणा" },
    { text: "ज़मीं पर बैठ कर ख़्वाब-ए-फ़लक देखना, इक दिन इन ख़्वाबों को हक़ीक़त करना।", author: "अज्ञात", category: "प्रेरणा" },
    { text: "इश्क़ पर ज़ोर नहीं, है ये वो आतिश ग़ालिब, जो लगाए न लगे और बुझाए न बने।", author: "मिर्ज़ा ग़ालिब", category: "इश्क़" },
    { text: "बेख़ुदी बेसबब नहीं ग़ालिब, कुछ तो है जिसकी पर्दादारी है।", author: "मिर्ज़ा ग़ालिब", category: "ग़ज़ल" },
    { text: "मैं अकेला ही चला था जानिब-ए-मंज़िल मगर, लोग साथ आते गए और कारवाँ बनता गया।", author: "मजरूह सुल्तानपुरी", category: "प्रेरणा" },
    { text: "हर ज़र्रे में एक शमा जलती है, हर बूँद में एक समन्दर है, जिसने अपने अंदर झाँक कर देखा, उसने पूरी कायनात देख ली।", author: "अज्ञात", category: "सूफ़ी" },
    { text: "ख़ुश रहो अहल-ए-वतन ग़ालिब तो है बदनाम अपना, पर ये दिल है कि दुआ करता है सबके नाम।", author: "मिर्ज़ा ग़ालिब", category: "ग़ज़ल" },
    { text: "तेरे वादे पर जिए हम तो ये जान झूठ जाना, कि ख़ुशी से मर न जाते अगर ऐतबार होता।", author: "मिर्ज़ा ग़ालिब", category: "इश्क़" },
    { text: "वो एक मस्जिद से बुतख़ाने की तरफ़ आता है ग़ालिब, किसी को क्या पता उसकी इबादत क्या है।", author: "मिर्ज़ा ग़ालिब", category: "सूफ़ी" },
    { text: "हमने इस इश्क़ में क्या क्या ना सहा, बात तो एक ही थी पर बार-बार कही।", author: "अज्ञात", category: "इश्क़" },
    { text: "गुज़रता वक़्त भी ठहर गया है, किसी ने मेरी तरफ़ देखा है ज़रूर।", author: "अज्ञात", category: "इश्क़" },
    { text: "कभी ऐ हक़ीक़त-ए-मुन्तज़िर नज़र आ लिबास-ए-मजाज़ में, कि हज़ारों सजदे तड़प रहे हैं मेरी जबीन-ए-नियाज़ में।", author: "अल्लामा इक़बाल", category: "सूफ़ी" },
    { text: "ज़िन्दगी जीने के दो ही तरीक़े हैं, एक जो हो रहा है होने दो बर्दाश्त करो, दूसरा ज़िम्मेदारी उठाओ उसे बदलो।", author: "अज्ञात", category: "ज़िन्दगी" },
    { text: "तू इधर उधर की ना बात कर ये बता कि काफ़िला क्यूँ लुटा, मुझे रहज़नों से गिला नहीं तेरी रहबरी का सवाल है।", author: "अल्लामा इक़बाल", category: "प्रेरणा" },
    { text: "जो मिले हैं वो कहते हैं कि ग़ालिब कोई है, बे-नमक़ सा एक शख़्स मीर भी था।", author: "मिर्ज़ा ग़ालिब", category: "ग़ज़ल" },
    { text: "ये फ़ितना आदमी की ख़ानाविरानी को क्या कम है, हुए तुम दोस्त जिसके, उसे दुश्मन समझता हूँ।", author: "मिर्ज़ा ग़ालिब", category: "ग़ज़ल" },
    { text: "ज़ेहाल-ए-मिस्कीन मकुन तग़ाफ़ुल, दुराये नैना बनाये बतियाँ।", author: "अमीर ख़ुसरो", category: "सूफ़ी" },
    { text: "ख़ुदा के वास्ते पर्दा न काबे से उठा ज़ालिम, कहीं ऐसा न हो यां भी वही काफ़िर सनम निकले।", author: "मिर्ज़ा ग़ालिब", category: "ग़ज़ल" },
    { text: "ज़रा सी बात पे बरसों का याराना भूला दे, ज़रा सी बात पे बरसों के बेगाने अपने हो जाएं।", author: "अज्ञात", category: "ज़िन्दगी" },
    { text: "हम हैं मुश्ताक़ और वो बेज़ार, या इलाही ये माजरा क्या है।", author: "मिर्ज़ा ग़ालिब", category: "इश्क़" },
    { text: "दुनिया की मोहब्बत में जो डूबे हुए हैं वो, क़िस्सा बन गए पर कहानी नहीं बदली।", author: "अज्ञात", category: "ज़िन्दगी" },
    { text: "ज़िन्दगी बहुत कम है ग़ैरों को ख़ुश करने के लिए, अपनों को वक़्त दो ज़माने का क्या है आता जाता रहेगा।", author: "अज्ञात", category: "ज़िन्दगी" },
    { text: "हर फ़िक्र को धुएँ में उड़ाता चला गया, मैं ज़िन्दगी का साथ निभाता चला गया।", author: "साहिर लुधियानवी", category: "ज़िन्दगी" },
    { text: "अपनी मर्ज़ी से कहाँ अपने सफ़र के हम हैं, रुख़ हवाओं का जिधर का है उधर के हम हैं।", author: "बशीर बद्र", category: "ग़ज़ल" },
    { text: "कोई हाथ भी न मिलाएगा जो गले मिलोगे तपाक से, ये नए मिज़ाज का शहर है ज़रा फ़ासले से मिला करो।", author: "बशीर बद्र", category: "ज़िन्दगी" },
    { text: "बड़े बेआबरू होकर तेरे कूचे से हम निकले, बहुत निकले मेरे अरमान लेकिन फिर भी कम निकले।", author: "मिर्ज़ा ग़ालिब", category: "ग़ज़ल" },
    { text: "मैं नशे में हूँ मगर होश ज़रा देख तो ले, कौन कहता है कि बस पीने वाले पीते हैं।", author: "अज्ञात", category: "सूफ़ी" },
    { text: "ज़मीन-ओ-ज़मां कोई और है, मेरे ज़ेहन में कोई और है, किसे ढूँढता है ये दिल मेरा, न पता न नाम न निशां कोई।", author: "अज्ञात", category: "सूफ़ी" },
    { text: "दर्द-ए-दिल लिखूँ कब तक जाऊँ उनको दिखा दूँ, उंगलियाँ फ़िग़ार अपनी ख़ामा-ए-ख़ूँचकाँ अपना।", author: "मिर्ज़ा ग़ालिब", category: "ग़ज़ल" },
    { text: "हम परवर्दा-ए-नाज़ हैं ग़म क्या, ग़म हमें हो तो ग़म ख़ुदा जाने।", author: "मीर तक़ी मीर", category: "ग़ज़ल" },
    { text: "दुनिया ने किसी को कुछ नहीं दिया, खुद से जो मिला है कमाई है, बाकी सब उधारी है।", author: "अज्ञात", category: "ज़िन्दगी" },
    { text: "बात करने का अगर शौक़ है तो ख़ामोश रहो, पहले सुनना सीखो बोलना ख़ुद आ जाएगा।", author: "अज्ञात", category: "ज़िन्दगी" },
  ],
};

export const LANGUAGE_CONFIG = {
  english: { label: "English Quotes", icon: "✨", gradient: "linear-gradient(135deg, #0f2027 0%, #203a43 40%, #2c5364 100%)" },
  hindi: { label: "Hindi — कविता · दोहे · मुहावरे", icon: "🪷", gradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 40%, #e94560 100%)" },
  sanskrit: { label: "Sanskrit — श्लोक", icon: "🕉️", gradient: "linear-gradient(135deg, #2d1b69 0%, #4a1942 40%, #6b2fa0 100%)" },
  urdu: { label: "Urdu — शायरी", icon: "🌙", gradient: "linear-gradient(135deg, #1b1b2f 0%, #162447 40%, #1f4068 100%)" },
};

export const CATEGORY_COLORS = {
  Motivation: "#f59e0b", Life: "#10b981", Success: "#3b82f6", Wisdom: "#8b5cf6",
  Courage: "#ef4444", Persistence: "#f97316", Dreams: "#ec4899",
  "कविता": "#e11d48", "प्रेरणा": "#f59e0b", "दोहा": "#8b5cf6", "मुहावरा": "#10b981",
  "कर्म": "#ef4444", "आत्मज्ञान": "#3b82f6", "विद्या": "#f97316", "सत्य": "#10b981",
  "धर्म": "#8b5cf6", "कल्याण": "#ec4899", "योग": "#06b6d4",
  "ग़ज़ल": "#e11d48", "इश्क़": "#ec4899", "ज़िन्दगी": "#10b981", "सूफ़ी": "#8b5cf6",
};
